// next.config.js
module.exports = {
  env: {
    NEXT_PUBLIC_AGENTD_API_URL: process.env.NEXT_PUBLIC_AGENTD_API_URL,
    NEXT_PUBLIC_WS_URL: process.env.NEXT_PUBLIC_WS_URL,
    NEXT_PUBLIC_API_TIMEOUT: process.env.NEXT_PUBLIC_API_TIMEOUT,
    NEXT_PUBLIC_MAX_RECONNECT_ATTEMPTS: process.env.NEXT_PUBLIC_MAX_RECONNECT_ATTEMPTS,
    NEXT_PUBLIC_RECONNECT_INTERVAL: process.env.NEXT_PUBLIC_RECONNECT_INTERVAL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
    NEXT_PUBLIC_DEBUG: process.env.NEXT_PUBLIC_DEBUG,
  },
  allowedDevOrigins: ['127.0.0.1'],
};