#!/usr/bin/env bash
# PolyMind devcontainer 首次创建后的初始化脚本，可重复执行
set -euo pipefail
cd /workspaces/polymind

echo "=== PolyMind devcontainer: post-create setup ==="

# 1. Linux 宿主机的 bind mount 会保留宿主 UID，工作区可能不可写
if [ ! -w . ]; then
  echo "[fix] Workspace not writable — adjusting ownership..."
  sudo chown -R "$(id -u):$(id -g)" /workspaces/polymind 2>/dev/null || {
    echo "WARNING: Could not adjust workspace ownership."
    echo "Run manually:  sudo chown -R node:node /workspaces/polymind"
  }
fi

# 2. 修复命名卷挂载点属主：旧版本创建的卷属主为 root，会导致 pnpm install 报 EACCES
for dir in "${PNPM_HOME:-$HOME/.local/share/pnpm}" "node_modules"; do
  if [ -d "$dir" ] && [ ! -w "$dir" ]; then
    echo "[fix] Granting write access to $dir"
    sudo chown -R "$(id -u):$(id -g)" "$dir" 2>/dev/null || {
      echo "WARNING: Could not adjust ownership of $dir."
    }
  fi
done

# 3. 清理属主异常或残留的 .next/ 构建缓存
if [ -d .next ] && [ ! -w .next ]; then
  echo "[fix] Removing stale .next/ with wrong ownership..."
  sudo rm -rf .next 2>/dev/null || rm -rf .next 2>/dev/null || true
fi
if [ -d .next ]; then
  rm -rf .next/cache 2>/dev/null || true
fi

# 4. .env 不存在时按模板生成（不覆盖已有配置）
#    默认连公网技能市场；与本地 witty-service（默认 8000 端口）联调时改为 127.0.0.1:8000
if [ ! -f .env ]; then
  cat > .env << 'EOF'
NEXT_PUBLIC_AGENTD_API_URL=http://127.0.0.1:8000
NEXT_PUBLIC_WS_URL=ws://127.0.0.1:8000/ws
NEXT_PUBLIC_API_TIMEOUT=120000
NEXT_PUBLIC_MAX_RETRY_ATTEMPTS=3
NEXT_PUBLIC_RECONNECT_INTERVAL=3000
NEXT_PUBLIC_MAX_RECONNECT_ATTEMPTS=5
NEXT_WITTYHUB_API_URL=https://skillhub.openeuler.org
NEXT_PUBLIC_AUTH_TOKEN=dev-token
EOF
  echo "[ok] Created .env from devcontainer template (see .env.example for all options)"
else
  echo "[ok] .env already exists — keeping existing configuration"
fi

# 5. 清理客户端带入的不可达 git 代理。VS Code 默认把客户端（Windows/macOS）的 ~/.gitconfig
#    复制进容器（dev.containers.copyGitConfig）。若其中配了 127.0.0.1 本地代理，在 host 网络的
#    容器里该地址指向虚机自身而非客户端；代理不可达时 pre-commit 拉取 hook 仓库会直接失败。
#    http.proxy 与 https.proxy 任一探测失败即全部清理（两者通常指向同一代理）
for proxy_key in http.proxy https.proxy; do
  git_proxy=$(git config --global --get "$proxy_key" 2>/dev/null) || continue
  [ -n "$git_proxy" ] || continue
  proxy_hostport=${git_proxy#*://}; proxy_hostport=${proxy_hostport%%/*}
  proxy_host=${proxy_hostport%:*}; proxy_port=${proxy_hostport##*:}
  case "$proxy_host" in
    127.0.0.1|localhost)
      if timeout 2 bash -c "exec 3<>/dev/tcp/${proxy_host}/${proxy_port}" 2>/dev/null; then
        echo "[ok] git 代理 ${git_proxy} 可达，保持现有配置"
      else
        echo "[fix] git 代理 ${git_proxy} 不可达（host 网络下指向虚机自身），已清理 http.proxy / https.proxy"
        git config --global --unset http.proxy || true
        git config --global --unset https.proxy || true
        break
      fi
      ;;
  esac
done

# 6. 启用仓库自带的 Git 提交钩子（容器全局 core.hooksPath=.githooks），并预热 hook 环境
#    （clone 各 hook 仓库、go 构建等），避免首次提交时才触发耗时的联网安装；失败不阻断创建
if command -v pre-commit >/dev/null 2>&1; then
  git config --global core.hooksPath .githooks
  echo "[ok] core.hooksPath=.githooks ($(pre-commit --version) at $(command -v pre-commit))"
  pre-commit install-hooks \
    || echo "[warn] pre-commit hook 环境预热失败，首次提交时会重试（检查 GOPROXY / 网络连通性）"
else
  echo "[warn] pre-commit 缺失，钩子不会生效 — 见 .devcontainer/README.md「Git 提交钩子未生效」"
fi

# 7. 旧版脚本用 `pre-commit install` 把容器解释器路径写进了宿主机 .git/hooks，钩子如今改由
#    .githooks/ 接管。此处只提示、不代删（不写宿主机文件）
if [ -f .git/hooks/pre-commit ] && grep -q 'File generated by pre-commit' .git/hooks/pre-commit 2>/dev/null; then
  echo "[note] 宿主机 .git/hooks 残留旧版 pre-commit hook；若宿主机提交报错，执行："
  echo "         pre-commit uninstall -t pre-commit -t commit-msg"
fi

# 8. 安装依赖（pnpm 内置网络自动重试；npm 源已写入镜像内的 ~/.npmrc）
echo "[run] pnpm install (registry: $(pnpm config get registry))"
if ! pnpm install --prefer-offline --reporter=append-only --fetch-retries=5; then
  echo "ERROR: pnpm install failed." >&2
  echo "  registry: $(pnpm config get registry)" >&2
  echo "  If this is a permissions error, rebuild after running:" >&2
  echo "    docker volume rm polymind_pnpm_store polymind_node_modules" >&2
  exit 1
fi

# 9. 输出工具链版本，便于与 CI 比对
echo "--- Toolchain versions ---"
node --version
pnpm --version
command -v pre-commit >/dev/null 2>&1 && pre-commit --version || echo "pre-commit: MISSING"

echo ""
echo "PolyMind devcontainer ready. Run:  pnpm dev"
